### ISSUE TITLE
DatasetCreator generates more data than samples in the dataset

### ISSUE THREAD

**Issue by EvanSpector** [TorchDSP/torchsig#68] opened 2023-04-26 15:54 UTC
It seems to generate (num_workers + batch_size) times more data than is specified in the dataset num_samples.

**Comment by gvanhoy** [comment] 2023-04-26 16:36
@EvanSpector Thanks for making the issue. Any information on the platform?

**Comment by EvanSpector** [comment] 2023-04-26 17:41
Thanks for your work on this repo

AlmaLinux 8.6
CPU: AMD Ryzen 9 3900X

**Comment by gvanhoy** [comment] 2023-05-02 15:26
Although I suspected this could be an issue, I cannot reproduce this using different multiprocessing contexts or hard-coding different ```num_workers``` or ```batch_size``` within the PyTorch DataLoader.

**Comment by gvanhoy** [comment] 2023-05-23 13:48
Closing because I cannot reproduce.

**Closed by gvanhoy** 2023-05-23 13:48 UTC
Labels: help wanted
