### ISSUE TITLE
Sig53 Dataset issue

### ISSUE THREAD

**Issue by Jie-su** [TorchDSP/torchsig#22] opened 2022-11-30 05:16 UTC
Hi,

I am trying to use Sig53 datasets for my research, but I met some problems with it. 

1.  Does the sig53 equal to WidebandSig53? Since the impaired version of WindebandSig53 only consists of 250000 samples with a length of 262144. However, sig53 contains 5.2M samples in the paper.

2. The WidebandSig53 dataset's target contains multi-labels (as a list), and there are no documents related to the transformation.

Thanks,

Jie,

**Comment by lboegner** [comment] 2022-11-30 21:13
Hi Jie-su,

Glad to hear you’re interested in Sig53 for your research!

1. Sig53 and WidebandSig53 are two different datasets:

    - Sig53 contains shorter examples of 4,096 IQ samples with a single signal class in each. This dataset is primarily meant to be used for signal classification research. More details on this dataset can be found in this paper: https://arxiv.org/pdf/2207.09918.pdf

    - WidebandSig53, on the other hand, contains longer examples of 262,144 IQ samples with potentially multiple, non-overlapping (in time and frequency) signal classes present. This dataset is primarily meant to be used for signal detection & signal recognition research. More details on this dataset can be found in this paper: https://arxiv.org/pdf/2211.10335.pdf

2. If using the SignalData object, the label for the WidebandSig53 dataset will be a list of SignalDescriptions, where each signal present in the data example has a SignalDescription element in the list. The WidebandSig53 dataset uses the DescToListTuple target transform at generation time, so when it is stored to disc, each example’s label is saved as a list of lists (rather than a list of SignalDescriptions), where the inner lists encompass the signal class, start, stop, center frequency, bandwidth, and SNR of each individual signal in the example.

Since I think the “issue” here is that we need better dataset documentation, I think we can close this as a duplicate of the existing issue @gvanhoy opened “Documentation: Better Dataset Documentation #18." Feel free to continue commenting with further questions in the meantime!

**Comment by Jie-su** [comment] 2022-12-01 03:37
Hi,

Thanks for your explanation.

But I can't see how to generate Sig53 from the documentation, so does it already released or not?

Thanks,

Jie

**Comment by Jie-su** [comment] 2022-12-02 01:47
Thanks！

Jie

**Closed** 2022-12-02 01:47 UTC
