### ISSUE TITLE
Some signals seem to be divided into two parts

### ISSUE THREAD

**Issue by slightY** [TorchDSP/torchsig#233] opened 2024-04-29 14:38 UTC
There is a situation where the signal is divided into two parts in some time-frequency images.
![1714401012448](https://github.com/TorchDSP/torchsig/assets/49468645/471e297b-0132-420a-915c-fd10acb072e8)

I'm not sure if the model will recognize it as two signals, but I think they belong to the same signal
I would like to ask why such a situation appears in the time-frequency image.

**Comment by MattCarrickPL** [comment] 2024-08-19 13:27
The issue is that we are trying to simulate a signal at the sampling rate boundary and to avoid all aliasing an ideal LPF is needed but that's impossible to build. So there will always be some energy that wraps around the -fs/2 and +fs/2 boundary. However, we've added in better filtering to cover this exact case in 0.5.2, so it's been addressed and I'm closing out the issue.

**Closed by MattCarrickPL** 2024-08-19 13:27 UTC
